# Utilisez une image Python officielle comme base
FROM python:3.9

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le script serveur1_pong.py dans le conteneur
COPY serveur1_ping.py /app/
#COPY serveur2_pong.py /app/
#COPY serveur3_annuaire.py /app/



# Installez les dépendances, si nécessaire
# (dans ce cas, vous n'avez besoin d'installer que les modules Python utilisés dans votre script)

# Exposez le port sur lequel le serveur écoute
EXPOSE 4567
#EXPOSE 5372
#EXPOSE 8080

# Commande à exécuter lorsque le conteneur démarre
CMD ["python", "serveur1_ping.py"]
#CMD ["python", "serveur2_pong.py"]
#CMD ["python", "serveur3_annuaire.py"]